RPS-1 add solana client for basic operation
rarible/blockchain-scanner pull request #27
Opened 2021-12-02 16:58 UTC by enslinmike

2021-12-02 18:27 UTC, evgenynacu requested changes

2021-12-02 18:27 UTC, evgenynacu commented on solana/pom.xml
> +            <groupId>io.ktor</groupId>
We use spring web client everywhere. Let's stick with it. I think no need to use new library

2021-12-02 18:27 UTC, evgenynacu commented on solana/src/main/kotlin/com/rarible/blockchain/solana/client/SolanaApi.kt
> +            val slot = getLatestSlot()
I think we can optimize here a little bit: do not try to load block if latest slot is the same as previous time

2021-12-03 06:53 UTC, yakischik approved these changes

2021-12-03 06:53 UTC, yakischik commented on solana/pom.xml
> +        <dependency>
Most of these dependencies already declared in core, check it please and remove re-declarations

2021-12-06 12:49 UTC, yakischik commented
We're working now in branch release/2.0, please re-create PR to it

2021-12-06 12:49 UTC, closed without merging